apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.wallpaper'
version = '0.1.0'

android {
  namespace 'expo.modules.wallpaper'
  compileSdk rootProject.ext.compileSdkVersion

  defaultConfig {
    minSdk rootProject.ext.minSdkVersion
    targetSdk rootProject.ext.targetSdkVersion
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
  kotlinOptions { jvmTarget = '17' }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
}
