/**
 * Pure helpers for the Live Darshan screens — no React, no network, so they are testable with
 * `node --test src/features/darshan/lib/live-logic.test.mjs`.
 */

export type StreamLike = {
  slug: string;
  templeName: string;
  place: string;
  categorySlug: string;
  state: 'live' | 'upcoming' | 'offline';
};

/** The list filter: `all`, `live`, or a category slug — plus an optional search text. */
export function filterStreams<T extends StreamLike>(streams: T[], filter: string, query = ''): T[] {
  const q = query.trim().toLowerCase();
  return streams.filter((s) => {
    if (filter === 'live' && s.state !== 'live') return false;
    if (filter !== 'all' && filter !== 'live' && s.categorySlug !== filter) return false;
    if (q && !`${s.templeName} ${s.place}`.toLowerCase().includes(q)) return false;
    return true;
  });
}

/** Streams that are on air right now. */
export const liveOnes = <T extends StreamLike>(streams: T[]): T[] => streams.filter((s) => s.state === 'live');

/** "HH:MM" (24h) -> minutes since midnight, or null if malformed. */
export function toMinutes(time: string): number | null {
  const m = /^(\d{1,2}):(\d{2})$/.exec(time.trim());
  if (!m) return null;
  const h = Number(m[1]);
  const min = Number(m[2]);
  return h > 23 || min > 59 ? null : h * 60 + min;
}

/** "18:45" -> `{ clock: '6:45', meridiem: 'pm' }` — the design sets the meridiem small under the time. */
export function clock12(time: string): { clock: string; meridiem: 'am' | 'pm' } {
  const mins = toMinutes(time);
  if (mins === null) return { clock: time, meridiem: 'am' };
  const h = Math.floor(mins / 60);
  const mm = String(mins % 60).padStart(2, '0');
  return { clock: `${h % 12 === 0 ? 12 : h % 12}:${mm}`, meridiem: h >= 12 ? 'pm' : 'am' };
}

/** "18:45" -> "6:45 pm". */
export function time12(time: string): string {
  const { clock, meridiem } = clock12(time);
  return `${clock} ${meridiem}`;
}

/** The wall-clock time a reminder for an aarti fires: `lead` minutes earlier, wrapping past midnight. */
export function reminderClock(time: string, lead = 10): { hour: number; minute: number } | null {
  const mins = toMinutes(time);
  if (mins === null) return null;
  const at = (mins - lead + 1440) % 1440;
  return { hour: Math.floor(at / 60), minute: at % 60 };
}

/** Storage key for one aarti of one stream. */
export const aartiKey = (streamSlug: string, time: string, name: string) => `${streamSlug}|${time}|${name}`;

/* ───────────────────────────────────────────────────── reminder state ── */

/** Persisted: aarti key -> the OS notification id that was scheduled for it. */
export type ReminderMap = Record<string, string>;

export const withReminder = (map: ReminderMap, key: string, id: string): ReminderMap => ({ ...map, [key]: id });

export function withoutReminder(map: ReminderMap, key: string): ReminderMap {
  const next = { ...map };
  delete next[key];
  return next;
}

/** Parses what was stored, dropping anything that is not string -> string. */
export function parseReminders(raw: string | null): ReminderMap {
  if (!raw) return {};
  try {
    const v = JSON.parse(raw) as unknown;
    if (!v || typeof v !== 'object' || Array.isArray(v)) return {};
    const out: ReminderMap = {};
    for (const [k, id] of Object.entries(v as Record<string, unknown>)) {
      if (typeof id === 'string' && id) out[k] = id;
    }
    return out;
  } catch {
    return {};
  }
}

/* ────────────────────────────────────────────────────────────── tones ── */

/** Warm gradient pairs for a stream with no cover — chosen by the slug so a stream keeps its colour. */
const TONES: readonly (readonly [string, string])[] = [
  ['#5A1A0C', '#C9661E'],
  ['#C98F1E', '#5A3A12'],
  ['#1F3550', '#C9A878'],
  ['#7A1C2A', '#E2744A'],
  ['#0F4A3A', '#7BC28F'],
  ['#2F3F7A', '#9BB5D8'],
];

export function toneFor(slug: string): readonly [string, string] {
  let h = 0;
  for (let i = 0; i < slug.length; i++) h = (h * 31 + slug.charCodeAt(i)) >>> 0;
  return TONES[h % TONES.length];
}

/** A compact count: 1.2K, 3.4M; null stays null (we never show a number we do not have). */
export function compactCount(n: number | null | undefined): string | null {
  if (typeof n !== 'number' || !Number.isFinite(n) || n < 0) return null;
  if (n < 1000) return String(Math.round(n));
  if (n < 1_000_000) return `${(n / 1000).toFixed(n < 10_000 ? 1 : 0).replace(/\.0$/, '')}K`;
  return `${(n / 1_000_000).toFixed(1).replace(/\.0$/, '')}M`;
}

/**
 * The player route. Typed routes are regenerated by the dev server, so a brand-new `[slug]` route is not
 * in the generated union until it next runs; the string is built here once instead of at every call site.
 */
export const playerHref = (slug: string) => `/darshan/${encodeURIComponent(slug)}` as never;
