import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export type Lang = 'en' | 'hi';

/** UI strings. Proper nouns (deity/temple names) stay in their own data. */
const STRINGS = {
  en: {
    // language screen
    lang_title: 'Choose your language',
    lang_sub: 'You can change this later',
    english: 'English',
    hindi: 'हिंदी',
    continue: 'Continue',
    // tabs
    tab_home: 'Home',
    tab_temples: 'Temples',
    tab_pooja: 'Pooja',
    tab_bhajan: 'Bhajan',
    tab_profile: 'Profile',
    tab_account: 'Account',
    // account / settings
    account_title: 'Account',
    settings: 'Settings',
    open_settings: 'Open Settings',
    reminders_blocked_title: 'Notifications are turned off',
    reminders_blocked_msg:
      'Aarti reminders arrive as notifications, so Android needs permission first. Turn them on in Settings and try again.',
    language: 'Language',
    sound: 'Sound',
    profile: 'Profile',
    edit_name: 'Edit name',
    save: 'Save',
    app_version: 'Pooja Mandir · v1.0',
    // brand + home
    brand: 'Shri Mandir',
    panchang: 'Panchang',
    tithi: 'Tithi',
    nakshatra: 'Nakshatra',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    popular_temples: 'Popular Temples',
    feat_virtual_pooja: 'Virtual Pooja',
    feat_bhajans: 'Bhajans',
    feat_echadhava: 'E-Chadhava',
    feat_journal: 'Daily Journal',
    daily_darshan: 'Daily Darshan',
    live: 'LIVE',
    // bhajan
    media_library: 'Premium Media Library',
    bhajan_empty: 'No bhajans on this shelf yet. They appear once the temple adds them.',
    morning_mantras: 'Morning Mantras',
    evening_aarti: 'Evening Aarti',
    meditation_music: 'Meditation Music',
    // profile menu
    my_poojas: 'My Poojas',
    my_poojas_sub: 'Upcoming & past bookings',
    saved_temples: 'Saved Temples',
    saved_temples_sub: 'Your spiritual destinations',
    daily_reminders: 'Daily Reminders',
    daily_reminders_sub: 'Aarti & Mantra alerts',
    language_pref: 'Language Preferences',
    help_support: 'Help & Support',
    help_support_sub: 'FAQs & Contact us',
    thought_of_day: 'Aaj ka Vichar',
    devotee: 'Devotee',
    // e-chadhava
    echadhava_title: 'E-Chadhava Offering',
    enter_amount: 'Enter Amount (₹)',
    amount: 'Amount',
    item: 'Item',
    off_flowers: 'Flowers',
    off_prasad: 'Prasad',
    off_vastram: 'Vastram',
    offering_amount: 'Offering Amount',
    service_fee: 'Service Fee (Secure)',
    total_payable: 'Total Payable',
    secure_payment: 'Secure Payment',
    pay_now: 'PAY NOW',
    payments_off: 'Payments disabled',
    payments_off_msg: 'Enable Payments in the Admin panel to checkout.',
    offering_received: 'Your offering has been received. Dhanyavaad!',
    // journal
    journal_title: 'Daily Spiritual Journal',
    mantras_chanted: 'Mantras Chanted',
    daily_gratitude: 'Daily Gratitude',
    grateful_ph: 'I am grateful for...',
    spiritual_notes: 'Spiritual Notes',
    reflect_ph: 'Reflect on your journey...',
    // darshan
    live_darshan: 'Live Darshan',
    views: 'Views',
    temple_announcement: 'Temple Announcement',
    announcement_text: 'Special Aarti today at 7 PM. Please participate online.',
    donate_now: 'Donate Now (E-Chadhava)',
    // temples list
    search_temples: 'Search Temples or Cities',
    near_me: 'Near Me',
    view_on_map: 'View on Map',
    stars_reviews_n: '{rating} stars ({count} reviews)',
    stars_only: '{rating} stars',
    away_suffix: '1.2 km away',
    away: 'away',
    appearance: 'Appearance',
    theme_system: 'System',
    theme_light: 'Light',
    theme_dark: 'Dark',
    rashifal: 'Horoscope',
    wallpaper: 'Wallpaper',
    alarm: 'Alarm',
    ringtone: 'Ringtone',
    status: 'Status',
    offering_to: 'Offering to',
    offer_chadhava: 'Offer',
    book_pooja_title: 'Book a Pooja',
    choose_seva: 'Choose a seva',
    choose_date: 'Choose a date',
    devotee_details: 'Devotee details',
    ph_gotra: 'Gotra (optional)',
    sankalp_note: 'Your name and gotra are recited during the sankalp.',
    prasad_delivery: 'Courier prasad to me',
    confirm_booking: 'Confirm & Pay',
    booking_done: 'Your seva is booked. Prasad will follow.',
    booking_off: 'Booking is not available at this temple yet.',
    performed_at: 'Performed at',
    nearest_first: 'Nearest first',
    locating: 'Finding you…',
    location_denied: 'Location is off — enable it in Settings',
    location_unavailable: 'Could not get a location fix',
    book_pooja: 'Book Pooja',
    navigate: 'Navigate',
    // my poojas
    my_poojas_title: 'My Booked Poojas',
    filter_all: 'All',
    filter_upcoming: 'Upcoming',
    filter_completed: 'Completed',
    no_bookings_title: 'No Poojas Booked Yet',
    no_bookings_desc: 'Book an authentic seva performed by temple priests with sacred sankalp in your name.',
    book_a_pooja: 'Book a Pooja',
    seva_date: 'Pooja Date',
    devotee_label: 'Devotee',
    gotra_label: 'Gotra',
    prasad_status: 'Prasad Status',
    prasad_opted: 'Prasad Included (Courier)',
    prasad_not_opted: 'No Prasad Delivery',
    booking_ref: 'Booking Ref',
    status_upcoming: 'Scheduled',
    status_completed: 'Completed 🙏',
    view_temple: 'View Temple',
    cancel_booking: 'Cancel Seva',
    booking_cancelled: 'Booking has been cancelled.',
    cancel_confirm_title: 'Cancel Seva?',
    cancel_confirm_msg: 'Are you sure you want to cancel this booked pooja?',
    // saved temples
    saved_temples_title: 'Saved Temples',
    no_saved_temples_title: 'No Saved Temples Yet',
    no_saved_temples_desc: 'Tap the heart icon on any temple card to bookmark your sacred destinations here.',
    explore_temples: 'Explore Temples',
    temple_saved_toast: 'Temple added to saved destinations',
    temple_unsaved_toast: 'Temple removed from saved destinations',
    // faqs & support
    faqs_title: 'Help & Support',
    faqs_header: 'Frequently Asked Questions',
    faqs_sub: 'Find answers to common questions about rituals, bookings, and prasad.',
    search_faqs: 'Search questions…',
    helpline_card_title: 'Devotee Care & Support',
    helpline_card_sub: 'Our seva team is available daily from 6:00 AM to 10:00 PM IST.',
    contact_support: 'Contact Support',
    copied_email: 'Support email copied',
    call_helpline: 'Call Helpline',
    // auth
    auth_title: 'Sign in / Sign up',
    auth_sub: 'Continue to darshan',
    login_selection_title: 'Login',
    login_with_mobile: 'Login with Mobile',
    login_with_google: 'Continue with Google',
    entry_mobile_title: 'Mobile Number Login',
    entry_email_title: 'Email Login',
    login_other: 'Login with other options',
    otp_verification: 'OTP Verification',
    otp_sub_to: 'Enter the 6-digit code sent to',
    verify_proceed: 'Verify & Proceed',
    create_profile: 'Create Profile',
    change_photo: 'Change Photo',
    full_name: 'Full Name',
    ph_full_name: 'Enter your full name',
    bio_label: 'Bio',
    ph_bio: 'Tell us about yourself...',
    complete_profile: 'Complete Profile',
    method_phone: 'Phone',
    method_email: 'Email',
    label_phone: 'Phone number',
    label_email: 'Email',
    ph_phone: '10-digit number',
    ph_email: 'you@example.com',
    send_otp: 'Send OTP',
    otp_title: 'Verify OTP',
    otp_sent: 'Sent to',
    otp_sms_note: 'We will send a one-time code by SMS.',
    resend_in: 'Resend code in',
    no_code: 'Didn\u2019t get the code?',
    verify: 'Verify',
    resend: 'Resend OTP',
    profile_title: 'Your details',
    profile_sub: 'Almost done',
    label_name: 'Your name',
    ph_name: 'Full name',
    finish: 'Finish',
    err_name: 'Please enter your name',
    err_email: 'Enter a valid email',
    err_phone: 'Enter a 10-digit number',
    err_otp: 'Wrong OTP',
    err_otp_expired: 'That code expired. Request a new one.',
    err_too_many: 'Too many attempts. Try again in a little while.',
    err_network: 'No connection. Check your internet and try again.',
    err_signin_failed: 'Sign-in failed. Please try again.',
    err_auth_unavailable: 'Sign-in is temporarily unavailable. Please try again later.',
    err_sms_region: 'SMS sign-in is not enabled for this region yet.',
    err_sms_billing: 'SMS sign-in is not available yet. Please use Google sign-in.',
    err_google_not_configured: 'Google sign-in is not set up in this build.',
    err_play_services: 'Google Play Services is required to sign in with Google.',
    err_blocked: 'This account has been blocked. Please contact support.',
    // temples
    pilgrimage_map: 'PILGRIMAGE MAP',
    choose_temple: 'Choose a temple',
    tap_marker: 'temples · tap a marker',
    reset_view: 'Reset view',
    perform_pooja: 'Perform Pooja',
    tap_to_begin: 'Tap a temple on the map to begin',
    // mandir
    drag_hint: 'Hold and rotate the thali',
    parikrama: 'parikrama',
    aarti_done: 'Aarti complete 🙏',
    listen: 'Listen now',
    stop: 'Stop',
    collection: 'Collection',
    auto_aarti: 'Auto Aarti',
    // general actions
    entry_saved: 'Entry saved 🙏',
    coming_soon: 'Coming soon',
    coming_soon_msg: 'This feature is being prepared for you.',
    // logout
    logout_title: 'Log out?',
    signed_in_as: 'Signed in as',
    cancel: 'Cancel',
    logout: 'Log out',
    switch_language: 'Switch to हिंदी',
  },
  hi: {
    lang_title: 'अपनी भाषा चुनें',
    lang_sub: 'आप इसे बाद में बदल सकते हैं',
    english: 'English',
    hindi: 'हिंदी',
    continue: 'आगे बढ़ें',
    tab_home: 'होम',
    tab_temples: 'मंदिर',
    tab_pooja: 'पूजा',
    tab_bhajan: 'भजन',
    tab_profile: 'प्रोफ़ाइल',
    tab_account: 'खाता',
    account_title: 'खाता',
    settings: 'सेटिंग्स',
    open_settings: 'सेटिंग्स खोलें',
    reminders_blocked_title: 'सूचनाएँ बंद हैं',
    reminders_blocked_msg:
      'आरती स्मरण सूचना के रूप में आते हैं, इसलिए Android की अनुमति आवश्यक है। सेटिंग्स में चालू करके पुनः प्रयास करें।',
    language: 'भाषा',
    sound: 'ध्वनि',
    profile: 'प्रोफ़ाइल',
    edit_name: 'नाम बदलें',
    save: 'सहेजें',
    app_version: 'पूजा मंदिर · v1.0',
    // brand + home
    brand: 'श्री मंदिर',
    panchang: 'पंचांग',
    tithi: 'तिथि',
    nakshatra: 'नक्षत्र',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    popular_temples: 'लोकप्रिय मंदिर',
    feat_virtual_pooja: 'वर्चुअल पूजा',
    feat_bhajans: 'भजन',
    feat_echadhava: 'ई-चढ़ावा',
    feat_journal: 'दैनिक जर्नल',
    daily_darshan: 'दैनिक दर्शन',
    live: 'लाइव',
    // bhajan
    media_library: 'प्रीमियम मीडिया लाइब्रेरी',
    bhajan_empty: 'इस श्रेणी में अभी कोई भजन नहीं। मंदिर द्वारा जोड़े जाते ही यहाँ दिखेंगे।',
    morning_mantras: 'प्रातः मंत्र',
    evening_aarti: 'संध्या आरती',
    meditation_music: 'ध्यान संगीत',
    // profile menu
    my_poojas: 'मेरी पूजाएँ',
    my_poojas_sub: 'आगामी और पिछली बुकिंग',
    saved_temples: 'सहेजे गए मंदिर',
    saved_temples_sub: 'आपके आध्यात्मिक गंतव्य',
    daily_reminders: 'दैनिक अनुस्मारक',
    daily_reminders_sub: 'आरती और मंत्र अलर्ट',
    language_pref: 'भाषा प्राथमिकताएँ',
    help_support: 'सहायता और समर्थन',
    help_support_sub: 'सामान्य प्रश्न और संपर्क',
    thought_of_day: 'आज का विचार',
    devotee: 'भक्त',
    // e-chadhava
    echadhava_title: 'ई-चढ़ावा अर्पण',
    enter_amount: 'राशि भरें (₹)',
    amount: 'राशि',
    item: 'वस्तु',
    off_flowers: 'पुष्प',
    off_prasad: 'प्रसाद',
    off_vastram: 'वस्त्र',
    offering_amount: 'अर्पण राशि',
    service_fee: 'सेवा शुल्क (सुरक्षित)',
    total_payable: 'कुल देय',
    secure_payment: 'सुरक्षित भुगतान',
    pay_now: 'अभी भुगतान करें',
    payments_off: 'भुगतान बंद है',
    payments_off_msg: 'चेकआउट के लिए एडमिन पैनल में भुगतान सक्षम करें।',
    offering_received: 'आपका अर्पण प्राप्त हुआ। धन्यवाद!',
    // journal
    journal_title: 'दैनिक आध्यात्मिक जर्नल',
    mantras_chanted: 'जप संख्या',
    daily_gratitude: 'दैनिक कृतज्ञता',
    grateful_ph: 'मैं आभारी हूँ...',
    spiritual_notes: 'आध्यात्मिक नोट्स',
    reflect_ph: 'अपनी यात्रा पर विचार करें...',
    // darshan
    live_darshan: 'लाइव दर्शन',
    views: 'दृश्य',
    temple_announcement: 'मंदिर घोषणा',
    announcement_text: 'आज शाम 7 बजे विशेष आरती। कृपया ऑनलाइन भाग लें।',
    donate_now: 'अभी दान करें (ई-चढ़ावा)',
    // temples list
    search_temples: 'मंदिर या शहर खोजें',
    near_me: 'मेरे पास',
    view_on_map: 'मानचित्र पर देखें',
    stars_reviews_n: '{rating} स्टार ({count} समीक्षाएँ)',
    stars_only: '{rating} स्टार',
    away_suffix: '1.2 कि.मी. दूर',
    away: 'दूर',
    appearance: 'रूप',
    theme_system: 'सिस्टम',
    theme_light: 'उजला',
    theme_dark: 'गहरा',
    rashifal: 'राशिफल',
    wallpaper: 'वॉलपेपर',
    alarm: 'अलार्म',
    ringtone: 'रिंगटोन',
    status: 'स्टेटस',
    offering_to: 'अर्पण',
    offer_chadhava: 'चढ़ावा',
    book_pooja_title: 'पूजा बुक करें',
    choose_seva: 'सेवा चुनें',
    choose_date: 'तिथि चुनें',
    devotee_details: 'भक्त का विवरण',
    ph_gotra: 'गोत्र (वैकल्पिक)',
    sankalp_note: 'संकल्प के समय आपका नाम और गोत्र पढ़ा जाएगा।',
    prasad_delivery: 'प्रसाद मुझे भेजें',
    confirm_booking: 'पुष्टि करें और भुगतान करें',
    booking_done: 'आपकी सेवा बुक हो गई है। प्रसाद भेजा जाएगा।',
    booking_off: 'इस मंदिर में बुकिंग अभी उपलब्ध नहीं है।',
    performed_at: 'यहाँ सम्पन्न',
    nearest_first: 'निकटतम पहले',
    locating: 'आपको ढूँढ रहे हैं…',
    location_denied: 'लोकेशन बंद है — सेटिंग्स में चालू करें',
    location_unavailable: 'लोकेशन नहीं मिल सकी',
    book_pooja: 'पूजा बुक करें',
    navigate: 'दिशा-निर्देश',
    // my poojas
    my_poojas_title: 'मेरी बुक की गई पूजाएँ',
    filter_all: 'सभी',
    filter_upcoming: 'आगामी',
    filter_completed: 'संपन्न',
    no_bookings_title: 'अभी कोई पूजा बुक नहीं है',
    no_bookings_desc: 'मंदिर के पुजारियों द्वारा अपने नाम पर पवित्र संकल्प के साथ प्रामाणिक सेवा बुक करें।',
    book_a_pooja: 'पूजा बुक करें',
    seva_date: 'पूजा तिथि',
    devotee_label: 'भक्त',
    gotra_label: 'गोत्र',
    prasad_status: 'प्रसाद स्थिति',
    prasad_opted: 'प्रसाद शामिल (कूरियर)',
    prasad_not_opted: 'प्रसाद नहीं चुना गया',
    booking_ref: 'बुकिंग संदर्भ',
    status_upcoming: 'निर्धारित',
    status_completed: 'संपन्न 🙏',
    view_temple: 'मंदिर देखें',
    cancel_booking: 'सेवा रद्द करें',
    booking_cancelled: 'बुकिंग सफलतापूर्वक रद्द कर दी गई।',
    cancel_confirm_title: 'सेवा रद्द करें?',
    cancel_confirm_msg: 'क्या आप इस बुक की गई पूजा को रद्द करना चाहते हैं?',
    // saved temples
    saved_temples_title: 'सहेजे गए मंदिर',
    no_saved_temples_title: 'अभी कोई मंदिर सहेजा नहीं गया है',
    no_saved_temples_desc: 'अपने पसंदीदा तीर्थ स्थलों को यहाँ सहेजने के लिए किसी भी मंदिर कार्ड पर दिल के आइकन को टैप करें।',
    explore_temples: 'मंदिर देखें',
    temple_saved_toast: 'मंदिर सहेजे गए स्थलों में जोड़ा गया',
    temple_unsaved_toast: 'मंदिर सहेजे गए स्थलों से हटाया गया',
    // faqs & support
    faqs_title: 'सहायता और संपर्क',
    faqs_header: 'अक्सर पूछे जाने वाले प्रश्न',
    faqs_sub: 'अनुष्ठानों, बुकिंग और प्रसाद के बारे में सामान्य प्रश्नों के उत्तर पाएँ।',
    search_faqs: 'प्रश्न खोजें…',
    helpline_card_title: 'भक्त सहायता एवं सेवा',
    helpline_card_sub: 'हमारी सेवा टीम प्रतिदिन सुबह 6:00 से रात 10:00 बजे तक उपलब्ध है।',
    contact_support: 'सहायता से संपर्क करें',
    copied_email: 'सहायता ईमेल कॉपी किया गया',
    call_helpline: 'हेल्पलाइन पर कॉल करें',
    auth_title: 'साइन इन / साइन अप',
    auth_sub: 'दर्शन जारी रखने के लिए',
    login_selection_title: 'लॉगिन चयन',
    login_with_mobile: 'मोबाइल से लॉगिन करें',
    login_with_google: 'Google से जारी रखें',
    entry_mobile_title: 'मोबाइल नंबर लॉगिन',
    entry_email_title: 'ईमेल लॉगिन',
    login_other: 'अन्य विकल्पों से लॉगिन',
    otp_verification: 'OTP सत्यापन',
    otp_sub_to: '6 अंकों का कोड यहाँ भेजा गया',
    verify_proceed: 'सत्यापित करें और आगे बढ़ें',
    create_profile: 'प्रोफ़ाइल बनाएँ',
    change_photo: 'फ़ोटो बदलें',
    full_name: 'पूरा नाम',
    ph_full_name: 'अपना पूरा नाम भरें',
    bio_label: 'परिचय',
    ph_bio: 'अपने बारे में बताएँ...',
    complete_profile: 'प्रोफ़ाइल पूर्ण करें',
    method_phone: 'फ़ोन',
    method_email: 'ईमेल',
    label_phone: 'फ़ोन नंबर',
    label_email: 'ईमेल',
    ph_phone: '10 अंकों का नंबर',
    ph_email: 'you@example.com',
    send_otp: 'OTP भेजें',
    otp_title: 'OTP सत्यापन',
    otp_sent: 'भेजा गया',
    otp_sms_note: 'हम SMS द्वारा एक बार का कोड भेजेंगे।',
    resend_in: 'कोड दोबारा भेजें',
    no_code: 'कोड नहीं मिला?',
    verify: 'सत्यापित करें',
    resend: 'OTP दोबारा भेजें',
    profile_title: 'अपनी जानकारी भरें',
    profile_sub: 'लगभग हो गया',
    label_name: 'आपका नाम',
    ph_name: 'पूरा नाम',
    finish: 'पूर्ण करें',
    err_name: 'कृपया अपना नाम भरें',
    err_email: 'सही ईमेल भरें',
    err_phone: '10 अंकों का नंबर भरें',
    err_otp: 'गलत OTP',
    err_otp_expired: 'यह कोड समाप्त हो गया। नया कोड मँगवाएँ।',
    err_too_many: 'बहुत अधिक प्रयास। थोड़ी देर बाद कोशिश करें।',
    err_network: 'कनेक्शन नहीं है। इंटरनेट जाँचकर पुनः प्रयास करें।',
    err_signin_failed: 'साइन इन विफल रहा। कृपया पुनः प्रयास करें।',
    err_auth_unavailable: 'साइन इन अभी उपलब्ध नहीं है। कृपया बाद में प्रयास करें।',
    err_sms_region: 'इस क्षेत्र के लिए SMS साइन इन अभी चालू नहीं है।',
    err_sms_billing: 'SMS साइन इन अभी उपलब्ध नहीं है। कृपया Google से साइन इन करें।',
    err_google_not_configured: 'इस बिल्ड में Google साइन इन सेट नहीं है।',
    err_play_services: 'Google से साइन इन करने के लिए Google Play Services आवश्यक है।',
    err_blocked: 'यह खाता अवरुद्ध कर दिया गया है। कृपया सहायता से संपर्क करें।',
    pilgrimage_map: 'तीर्थ मानचित्र',
    choose_temple: 'मंदिर चुनें',
    tap_marker: 'मंदिर · मार्कर दबाएँ',
    reset_view: 'रीसेट',
    perform_pooja: 'पूजा करें',
    tap_to_begin: 'शुरू करने के लिए मानचित्र पर मंदिर चुनें',
    drag_hint: 'थाली को पकड़कर घुमाएँ',
    parikrama: 'परिक्रमा',
    aarti_done: 'आरती सम्पन्न 🙏',
    listen: 'अभी सुनें',
    stop: 'बंद करें',
    collection: 'संग्रह',
    auto_aarti: 'ऑटो आरती',
    // general actions
    entry_saved: 'प्रविष्टि सहेजी गई 🙏',
    coming_soon: 'जल्द आ रहा है',
    coming_soon_msg: 'यह सुविधा आपके लिए तैयार की जा रही है।',
    logout_title: 'लॉग आउट करें?',
    signed_in_as: 'साइन इन',
    cancel: 'रद्द करें',
    logout: 'लॉग आउट',
    switch_language: 'Switch to English',
  },
} as const;

export type StringKey = keyof (typeof STRINGS)['en'];

type LanguageContextValue = {
  lang: Lang | null;
  loading: boolean;
  setLang: (l: Lang) => Promise<void>;
  toggleLang: () => Promise<void>;
  t: (key: StringKey) => string;
};

const STORAGE_KEY = 'pooja.lang';

const LanguageContext = createContext<LanguageContextValue>({
  lang: null,
  loading: true,
  setLang: async () => {},
  toggleLang: async () => {},
  t: (k) => STRINGS.hi[k],
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((raw) => {
        if (raw === 'en' || raw === 'hi') setLangState(raw);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const setLang = useCallback(async (l: Lang) => {
    setLangState(l);
    await AsyncStorage.setItem(STORAGE_KEY, l).catch(() => {});
  }, []);

  const toggleLang = useCallback(async () => {
    const next: Lang = lang === 'en' ? 'hi' : 'en';
    await setLang(next);
  }, [lang, setLang]);

  const t = useCallback((key: StringKey) => STRINGS[lang ?? 'hi'][key], [lang]);

  const value = useMemo(
    () => ({ lang, loading, setLang, toggleLang, t }),
    [lang, loading, setLang, toggleLang, t],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
