import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export type Lang = 'en' | 'hi';

/** UI strings. Proper nouns (deity/temple names) stay in their own data. */
const STRINGS = {
  en: {
    // language screen
    lang_title: 'Choose your language',
    lang_sub: 'You can change this later',
    english: 'English',
    hindi: 'हिंदी',
    continue: 'Continue',
    // tabs
    tab_home: 'Home',
    tab_temples: 'Temples',
    tab_pooja: 'Pooja',
    tab_bhajan: 'Bhajan',
    tab_profile: 'Profile',
    tab_account: 'Account',
    // account / settings
    account_title: 'Account',
    settings: 'Settings',
    language: 'Language',
    sound: 'Sound',
    profile: 'Profile',
    edit_name: 'Edit name',
    save: 'Save',
    app_version: 'Pooja Mandir · v1.0',
    // brand + home
    brand: 'Shri Mandir',
    panchang: 'Panchang',
    tithi: 'Tithi',
    nakshatra: 'Nakshatra',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    popular_temples: 'Popular Temples',
    feat_virtual_pooja: 'Virtual Pooja',
    feat_bhajans: 'Bhajans',
    feat_echadhava: 'E-Chadhava',
    feat_journal: 'Daily Journal',
    daily_darshan: 'Daily Darshan',
    live: 'LIVE',
    // bhajan
    media_library: 'Premium Media Library',
    morning_mantras: 'Morning Mantras',
    evening_aarti: 'Evening Aarti',
    meditation_music: 'Meditation Music',
    // profile menu
    my_poojas: 'My Poojas',
    my_poojas_sub: 'Upcoming & past bookings',
    saved_temples: 'Saved Temples',
    saved_temples_sub: 'Your spiritual destinations',
    daily_reminders: 'Daily Reminders',
    daily_reminders_sub: 'Aarti & Mantra alerts',
    language_pref: 'Language Preferences',
    help_support: 'Help & Support',
    help_support_sub: 'FAQs & Contact us',
    thought_of_day: 'Aaj ka Vichar',
    devotee: 'Devotee',
    // e-chadhava
    echadhava_title: 'E-Chadhava Offering',
    enter_amount: 'Enter Amount (₹)',
    amount: 'Amount',
    item: 'Item',
    off_flowers: 'Flowers',
    off_prasad: 'Prasad',
    off_vastram: 'Vastram',
    offering_amount: 'Offering Amount',
    service_fee: 'Service Fee (Secure)',
    total_payable: 'Total Payable',
    secure_payment: 'Secure Payment',
    pay_now: 'PAY NOW',
    payments_off: 'Payments disabled',
    payments_off_msg: 'Enable Payments in the Admin panel to checkout.',
    offering_received: 'Your offering has been received. Dhanyavaad!',
    // journal
    journal_title: 'Daily Spiritual Journal',
    mantras_chanted: 'Mantras Chanted',
    daily_gratitude: 'Daily Gratitude',
    grateful_ph: 'I am grateful for...',
    spiritual_notes: 'Spiritual Notes',
    reflect_ph: 'Reflect on your journey...',
    // darshan
    live_darshan: 'Live Darshan',
    views: 'Views',
    temple_announcement: 'Temple Announcement',
    announcement_text: 'Special Aarti today at 7 PM. Please participate online.',
    donate_now: 'Donate Now (E-Chadhava)',
    // temples list
    search_temples: 'Search Temples or Cities',
    near_me: 'Near Me',
    view_on_map: 'View on Map',
    stars_reviews: '4.9 stars (25k reviews)',
    away_suffix: '1.2 km away',
    away: 'away',
    appearance: 'Appearance',
    theme_system: 'System',
    theme_light: 'Light',
    theme_dark: 'Dark',
    rashifal: 'Horoscope',
    wallpaper: 'Wallpaper',
    alarm: 'Alarm',
    ringtone: 'Ringtone',
    status: 'Status',
    offering_to: 'Offering to',
    offer_chadhava: 'Offer',
    book_pooja_title: 'Book a Pooja',
    choose_seva: 'Choose a seva',
    choose_date: 'Choose a date',
    devotee_details: 'Devotee details',
    ph_gotra: 'Gotra (optional)',
    sankalp_note: 'Your name and gotra are recited during the sankalp.',
    prasad_delivery: 'Courier prasad to me',
    confirm_booking: 'Confirm & Pay',
    booking_done: 'Your seva is booked. Prasad will follow.',
    booking_off: 'Booking is not available at this temple yet.',
    performed_at: 'Performed at',
    nearest_first: 'Nearest first',
    locating: 'Finding you…',
    location_denied: 'Location is off — enable it in Settings',
    location_unavailable: 'Could not get a location fix',
    book_pooja: 'Book Pooja',
    navigate: 'Navigate',
    // auth
    auth_title: 'Sign in / Sign up',
    auth_sub: 'Continue to darshan',
    login_selection_title: 'Login',
    login_with_mobile: 'Login with Mobile',
    login_with_email: 'Login with Email',
    entry_mobile_title: 'Mobile Number Login',
    entry_email_title: 'Email Login',
    login_other: 'Login with other options',
    otp_verification: 'OTP Verification',
    otp_sub_to: 'Enter the 4-digit code sent to',
    verify_proceed: 'Verify & Proceed',
    create_profile: 'Create Profile',
    change_photo: 'Change Photo',
    full_name: 'Full Name',
    ph_full_name: 'Enter your full name',
    bio_label: 'Bio',
    ph_bio: 'Tell us about yourself...',
    complete_profile: 'Complete Profile',
    method_phone: 'Phone',
    method_email: 'Email',
    label_phone: 'Phone number',
    label_email: 'Email',
    ph_phone: '10-digit number',
    ph_email: 'you@example.com',
    send_otp: 'Send OTP',
    otp_title: 'Verify OTP',
    otp_sent: 'Sent to',
    demo_otp: 'Demo OTP',
    verify: 'Verify',
    resend: 'Resend OTP',
    profile_title: 'Your details',
    profile_sub: 'Almost done',
    label_name: 'Your name',
    ph_name: 'Full name',
    finish: 'Finish',
    err_name: 'Please enter your name',
    err_email: 'Enter a valid email',
    err_phone: 'Enter a 10-digit number',
    err_otp: 'Wrong OTP',
    // temples
    pilgrimage_map: 'PILGRIMAGE MAP',
    choose_temple: 'Choose a temple',
    tap_marker: 'temples · tap a marker',
    reset_view: 'Reset view',
    perform_pooja: 'Perform Pooja',
    tap_to_begin: 'Tap a temple on the map to begin',
    // mandir
    drag_hint: 'Hold and rotate the thali',
    parikrama: 'parikrama',
    aarti_done: 'Aarti complete 🙏',
    listen: 'Listen now',
    stop: 'Stop',
    collection: 'Collection',
    auto_aarti: 'Auto Aarti',
    // logout
    logout_title: 'Log out?',
    signed_in_as: 'Signed in as',
    cancel: 'Cancel',
    logout: 'Log out',
    switch_language: 'Switch to हिंदी',
  },
  hi: {
    lang_title: 'अपनी भाषा चुनें',
    lang_sub: 'आप इसे बाद में बदल सकते हैं',
    english: 'English',
    hindi: 'हिंदी',
    continue: 'आगे बढ़ें',
    tab_home: 'होम',
    tab_temples: 'मंदिर',
    tab_pooja: 'पूजा',
    tab_bhajan: 'भजन',
    tab_profile: 'प्रोफ़ाइल',
    tab_account: 'खाता',
    account_title: 'खाता',
    settings: 'सेटिंग्स',
    language: 'भाषा',
    sound: 'ध्वनि',
    profile: 'प्रोफ़ाइल',
    edit_name: 'नाम बदलें',
    save: 'सहेजें',
    app_version: 'पूजा मंदिर · v1.0',
    // brand + home
    brand: 'श्री मंदिर',
    panchang: 'पंचांग',
    tithi: 'तिथि',
    nakshatra: 'नक्षत्र',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    popular_temples: 'लोकप्रिय मंदिर',
    feat_virtual_pooja: 'वर्चुअल पूजा',
    feat_bhajans: 'भजन',
    feat_echadhava: 'ई-चढ़ावा',
    feat_journal: 'दैनिक जर्नल',
    daily_darshan: 'दैनिक दर्शन',
    live: 'लाइव',
    // bhajan
    media_library: 'प्रीमियम मीडिया लाइब्रेरी',
    morning_mantras: 'प्रातः मंत्र',
    evening_aarti: 'संध्या आरती',
    meditation_music: 'ध्यान संगीत',
    // profile menu
    my_poojas: 'मेरी पूजाएँ',
    my_poojas_sub: 'आगामी और पिछली बुकिंग',
    saved_temples: 'सहेजे गए मंदिर',
    saved_temples_sub: 'आपके आध्यात्मिक गंतव्य',
    daily_reminders: 'दैनिक अनुस्मारक',
    daily_reminders_sub: 'आरती और मंत्र अलर्ट',
    language_pref: 'भाषा प्राथमिकताएँ',
    help_support: 'सहायता और समर्थन',
    help_support_sub: 'सामान्य प्रश्न और संपर्क',
    thought_of_day: 'आज का विचार',
    devotee: 'भक्त',
    // e-chadhava
    echadhava_title: 'ई-चढ़ावा अर्पण',
    enter_amount: 'राशि भरें (₹)',
    amount: 'राशि',
    item: 'वस्तु',
    off_flowers: 'पुष्प',
    off_prasad: 'प्रसाद',
    off_vastram: 'वस्त्र',
    offering_amount: 'अर्पण राशि',
    service_fee: 'सेवा शुल्क (सुरक्षित)',
    total_payable: 'कुल देय',
    secure_payment: 'सुरक्षित भुगतान',
    pay_now: 'अभी भुगतान करें',
    payments_off: 'भुगतान बंद है',
    payments_off_msg: 'चेकआउट के लिए एडमिन पैनल में भुगतान सक्षम करें।',
    offering_received: 'आपका अर्पण प्राप्त हुआ। धन्यवाद!',
    // journal
    journal_title: 'दैनिक आध्यात्मिक जर्नल',
    mantras_chanted: 'जप संख्या',
    daily_gratitude: 'दैनिक कृतज्ञता',
    grateful_ph: 'मैं आभारी हूँ...',
    spiritual_notes: 'आध्यात्मिक नोट्स',
    reflect_ph: 'अपनी यात्रा पर विचार करें...',
    // darshan
    live_darshan: 'लाइव दर्शन',
    views: 'दृश्य',
    temple_announcement: 'मंदिर घोषणा',
    announcement_text: 'आज शाम 7 बजे विशेष आरती। कृपया ऑनलाइन भाग लें।',
    donate_now: 'अभी दान करें (ई-चढ़ावा)',
    // temples list
    search_temples: 'मंदिर या शहर खोजें',
    near_me: 'मेरे पास',
    view_on_map: 'मानचित्र पर देखें',
    stars_reviews: '4.9 स्टार (25 हज़ार समीक्षाएँ)',
    away_suffix: '1.2 कि.मी. दूर',
    away: 'दूर',
    appearance: 'रूप',
    theme_system: 'सिस्टम',
    theme_light: 'उजला',
    theme_dark: 'गहरा',
    rashifal: 'राशिफल',
    wallpaper: 'वॉलपेपर',
    alarm: 'अलार्म',
    ringtone: 'रिंगटोन',
    status: 'स्टेटस',
    offering_to: 'अर्पण',
    offer_chadhava: 'चढ़ावा',
    book_pooja_title: 'पूजा बुक करें',
    choose_seva: 'सेवा चुनें',
    choose_date: 'तिथि चुनें',
    devotee_details: 'भक्त का विवरण',
    ph_gotra: 'गोत्र (वैकल्पिक)',
    sankalp_note: 'संकल्प के समय आपका नाम और गोत्र पढ़ा जाएगा।',
    prasad_delivery: 'प्रसाद मुझे भेजें',
    confirm_booking: 'पुष्टि करें और भुगतान करें',
    booking_done: 'आपकी सेवा बुक हो गई है। प्रसाद भेजा जाएगा।',
    booking_off: 'इस मंदिर में बुकिंग अभी उपलब्ध नहीं है।',
    performed_at: 'यहाँ सम्पन्न',
    nearest_first: 'निकटतम पहले',
    locating: 'आपको ढूँढ रहे हैं…',
    location_denied: 'लोकेशन बंद है — सेटिंग्स में चालू करें',
    location_unavailable: 'लोकेशन नहीं मिल सकी',
    book_pooja: 'पूजा बुक करें',
    navigate: 'दिशा-निर्देश',
    auth_title: 'साइन इन / साइन अप',
    auth_sub: 'दर्शन जारी रखने के लिए',
    login_selection_title: 'लॉगिन चयन',
    login_with_mobile: 'मोबाइल से लॉगिन करें',
    login_with_email: 'ईमेल से लॉगिन करें',
    entry_mobile_title: 'मोबाइल नंबर लॉगिन',
    entry_email_title: 'ईमेल लॉगिन',
    login_other: 'अन्य विकल्पों से लॉगिन',
    otp_verification: 'OTP सत्यापन',
    otp_sub_to: '4 अंकों का कोड यहाँ भेजा गया',
    verify_proceed: 'सत्यापित करें और आगे बढ़ें',
    create_profile: 'प्रोफ़ाइल बनाएँ',
    change_photo: 'फ़ोटो बदलें',
    full_name: 'पूरा नाम',
    ph_full_name: 'अपना पूरा नाम भरें',
    bio_label: 'परिचय',
    ph_bio: 'अपने बारे में बताएँ...',
    complete_profile: 'प्रोफ़ाइल पूर्ण करें',
    method_phone: 'फ़ोन',
    method_email: 'ईमेल',
    label_phone: 'फ़ोन नंबर',
    label_email: 'ईमेल',
    ph_phone: '10 अंकों का नंबर',
    ph_email: 'you@example.com',
    send_otp: 'OTP भेजें',
    otp_title: 'OTP सत्यापन',
    otp_sent: 'भेजा गया',
    demo_otp: 'डेमो OTP',
    verify: 'सत्यापित करें',
    resend: 'OTP दोबारा भेजें',
    profile_title: 'अपनी जानकारी भरें',
    profile_sub: 'लगभग हो गया',
    label_name: 'आपका नाम',
    ph_name: 'पूरा नाम',
    finish: 'पूर्ण करें',
    err_name: 'कृपया अपना नाम भरें',
    err_email: 'सही ईमेल भरें',
    err_phone: '10 अंकों का नंबर भरें',
    err_otp: 'गलत OTP',
    pilgrimage_map: 'तीर्थ मानचित्र',
    choose_temple: 'मंदिर चुनें',
    tap_marker: 'मंदिर · मार्कर दबाएँ',
    reset_view: 'रीसेट',
    perform_pooja: 'पूजा करें',
    tap_to_begin: 'शुरू करने के लिए मानचित्र पर मंदिर चुनें',
    drag_hint: 'थाली को पकड़कर घुमाएँ',
    parikrama: 'परिक्रमा',
    aarti_done: 'आरती सम्पन्न 🙏',
    listen: 'अभी सुनें',
    stop: 'बंद करें',
    collection: 'संग्रह',
    auto_aarti: 'ऑटो आरती',
    logout_title: 'लॉग आउट करें?',
    signed_in_as: 'साइन इन',
    cancel: 'रद्द करें',
    logout: 'लॉग आउट',
    switch_language: 'Switch to English',
  },
} as const;

export type StringKey = keyof (typeof STRINGS)['en'];

type LanguageContextValue = {
  lang: Lang | null;
  loading: boolean;
  setLang: (l: Lang) => Promise<void>;
  toggleLang: () => Promise<void>;
  t: (key: StringKey) => string;
};

const STORAGE_KEY = 'pooja.lang';

const LanguageContext = createContext<LanguageContextValue>({
  lang: null,
  loading: true,
  setLang: async () => {},
  toggleLang: async () => {},
  t: (k) => STRINGS.hi[k],
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((raw) => {
        if (raw === 'en' || raw === 'hi') setLangState(raw);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const setLang = useCallback(async (l: Lang) => {
    setLangState(l);
    await AsyncStorage.setItem(STORAGE_KEY, l).catch(() => {});
  }, []);

  const toggleLang = useCallback(async () => {
    const next: Lang = lang === 'en' ? 'hi' : 'en';
    await setLang(next);
  }, [lang, setLang]);

  const t = useCallback((key: StringKey) => STRINGS[lang ?? 'hi'][key], [lang]);

  const value = useMemo(
    () => ({ lang, loading, setLang, toggleLang, t }),
    [lang, loading, setLang, toggleLang, t],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
